# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.4.2
_src_path: git@github.com:ifegmbh/ife-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
customer_repo: false
enable_checklog_odoo: false
generate_requirements_txt: true
github_add_codeowners: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
is_enterprice_dependent: false
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: Niels Göttsch & Joachim Hänsel
org_slug: madmooose
rebel_module_groups: []
repo_description: ''
repo_name: ''
repo_slug: neunzig
repo_website: https://www.ziemlichoptimal.de
use_pyproject_toml: false
use_ruff: false

